name : Contest Service Test & Push Automation

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Contest-Service Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Action Started"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd services/contest
          npm i --frozen-lockfile
      - name: Run Tests
        run: |
          cd services/contest
          npm test
      - name: Endings
        run: echo "All Test Passed..."

  push-to-registry:
    needs: test
    name: Push Contest-Service to docker hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract meta information
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: itsarif/qcon
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: ./services/contest
        file: ./services/contest/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}


