name: Push to Public Registry

on:
  push:
    branches:
      - master

jobs:
  push-to-registry:
    name: Push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract meta information
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: itsarif/qcon
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context : ./api-gateway
          dockerfile: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}