name : QCon Tets Automation

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Api-Gateway Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Action Started"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd api-gateway  
          npm i --frozen-lockfile
      - name: Run Tests
        run: |
          cd api-gateway
          npm test
      - name: Endings
        run: echo "All Test Passed..."



