name : QCon Actions

on:
  push:
    branches:
      - master

jobs:
  test:
  runs-on: ubuntu-latest
  steps:
    - run: echo "Action Started"
    - name: Checkout
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm i --frozen-lockfile
    - name: Run Tests
      # run: test command
      run: echo "All Test Passed..."



